services:
  backend:
    env_file:
      - .env.prod
    environment:
      - HF_HUB_OFFLINE=1
      # Optional – nur wenn du wirklich einen HF-Hub-Cache montierst:
      # - HUGGINGFACE_HUB_CACHE=/huggingface_cache
    volumes:
      # Lokales Modell → einfacher, stabiler Container-Pfad
      - /workspace/hirsch/models/bge-reranker-large:/models/bge-reranker-large:ro
  
  mineru-sglang-server:
    image: mineru-sglang:latest
    # profiles: ["sglang"]   # ← ENTFERNEN
    ports:
      - "30001:30000"
    environment:
      MINERU_MODEL_SOURCE: local
    entrypoint: mineru-sglang-server
    command:
      - --host
      - 0.0.0.0
      - --port
      - "30000"
      - --mem-fraction-static
      - "0.5"
    shm_size: '32g'
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    networks:
      - rosti-net
    restart: unless-stopped
    cpuset: "20-39,60-79"
    # deploy: ...            # ← ENTFERNEN
    gpus: "device=1"
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=all


  ollama-serving:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    networks:
      - rosti-net
    restart: unless-stopped
    cpuset: "0-19,40-59"
    volumes:
      - /workspace/hirsch/models/ollama:/root/.ollama:ro
    # deploy: ...            # ← ENTFERNEN
    gpus: "device=0"
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all


  ollama-embedding:
    image: ollama/ollama:latest
    ports:
      - "11435:11434"
    networks:
      - rosti-net
    restart: unless-stopped
    volumes:
      - /workspace/hirsch/models/ollama:/root/.ollama:ro
    # deploy: ...            # ← ENTFERNEN
    gpus: "device=1"
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=all


  paddleocr:
    # image: <deins> / build: ... (nicht vergessen!)
    # deploy: ...            # ← ENTFERNEN
    gpus: "device=1"
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=all


  latexocr:
    image: jlh1024/latexocr-amd64-gpu:latest
    restart: unless-stopped
    environment:
      - DEVICE=cuda
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    # deploy: ...            # ← ENTFERNEN
    gpus: "device=1"



