# Developer: Jinglu Han
# mailbox: admin@de-manufacturing.cn

"""Add etag and is_third_party to file_gists

Revision ID: 4cde637703d1
Revises: 2a294f4b8f63
Create Date: 2025-08-09 16:28:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cde637703d1'
down_revision: Union[str, None] = '2a294f4b8f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_gists', sa.Column('etag', sa.String(length=255), nullable=True, comment='ETag of the file from MinIO for version tracking'))
    op.add_column('file_gists', sa.Column('is_third_party', sa.Boolean(), nullable=False, server_default=sa.text('0'), comment='Flag to indicate if the file is from a third-party source'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_gists', 'is_third_party')
    op.drop_column('file_gists', 'etag')
    # ### end Alembic commands ###