"""Drop legacy permission tables

Revision ID: 2a294f4b8f63
Revises: 
Create Date: 2025-08-09 16:18:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a294f4b8f63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    print("Dropping legacy table: role_permission_association")
    op.drop_table('role_permission_association')
    print("Dropping legacy table: permissions")
    op.drop_table('permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # We cannot fully restore these tables as the models are lost.
    # This is a one-way migration.
    pass
    # ### end Alembic commands ###